name: KBuild Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Install dependencies
        run: npm install

      - name: Build Android project
        run: |
          npx cap add android
          npx cap sync android

      - name: Build APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Save APK
        run: |
          mkdir -p apk-output
          cp android/app/build/outputs/apk/debug/app-debug.apk apk-output/KBuild-Network.apk
